In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from scipy import stats#or

In [4]:
import statistics as stats

# Mean

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
arr.mean()

3.0

In [7]:
arr1=np.array([1,2,3,4,5,500])

In [8]:
arr1.mean()

85.83333333333333

In [9]:
arr2=np.array([7,4,21,81,64,116])

In [10]:
arr2.mean()

48.833333333333336

In [11]:
arr3=np.array([12,16,84,69])

In [12]:
arr3.mean()

45.25

In [13]:
arr4=np.array([1,1,7,5,4,6])

In [14]:
np.median(arr4)

4.5

In [15]:
arr5=np.array([1,1,7,5,4])

In [16]:
np.median(arr5)

4.0

In [17]:
sers = pd.Series([1,1,7,5,4])
stats.mode(sers)

1

In [18]:
sers1 = pd.Series([1,1,2,2,7,5,4])# bimodal still gives only one mode
stats.mode(sers1)

1

# Quarniles

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
print(np.quantile(arr,0.25))

2.0


In [21]:
ar= pd.Series([1,2,3,4,5])
ar.quantile(0.25)

2.0

In [22]:
ar= pd.Series([1,3,25,49,5000])
ar.quantile(0.25)

3.0

In [24]:
sales=np.array([23,4,5232,43,666,896])

In [25]:
print("Range",sales.max()-sales.min())

Range 5228


In [26]:
arr

array([1, 2, 3, 4, 5])

In [27]:
arr.var()

2.0

In [30]:
arr1

array([  1,   2,   3,   4,   5, 500])

In [32]:
arr1.var()

34308.47222222222

In [33]:
ar2=np.array([1.1,1.2,1.3,1.4,1.5])

In [34]:
ar2.var()

0.01999999999999999

In [35]:
arr1.std()

185.22546321233003

In [36]:
ar2.std()

0.14142135623730948

In [37]:
arr.std()

1.4142135623730951

In [45]:
sal = np.array([32,34,54,654,78867,23435,46554,767,])
Q1 = np.quantile(sal,0.25)
Q3 = np.quantile(sal,0.75)
print("IQR:",Q3-Q1)
print(Q1)
print(Q3)

IQR: 29165.75
49.0
29214.75
