In [1]:
import numpy as np
from scipy import stats

In [2]:
array1=np.array([1,2,3,4,5])
array2=np.array([1,2,3,4,5,500])
array3=np.array([7,4,21,81,64,116])
array4=np.array([12,16,84,69])

In [3]:
print("Mean of array 1",np.mean(array1))
print("Mean of array 2",np.mean(array2))
print("Mean of array 3",np.mean(array3))
print("Mean of array 4",np.mean(array4))

Mean of array 1 3.0
Mean of array 2 85.83333333333333
Mean of array 3 48.833333333333336
Mean of array 4 45.25


In [4]:
print("Median of array 1",np.median(array1))
print("Median of array 2",np.median(array2))
print("Median of array 3",np.median(array3))
print("Median of array 4",np.median(array4))

Median of array 1 3.0
Median of array 2 3.5
Median of array 3 42.5
Median of array 4 42.5


In [5]:
array6=np.array([1,1,7,5,4,6])

In [6]:
array5=np.array([1,1,2,2,3,4,5])

In [7]:
print("mode of array 5",stats.mode(array5))

mode of array 5 ModeResult(mode=array([1]), count=array([2]))


In [8]:
print("mode of array 6",stats.mode(array6))

mode of array 6 ModeResult(mode=array([1]), count=array([2]))


In [9]:
print("Q1",np.quantile(array1,0.25))

Q1 2.0


In [10]:
print("Q2",np.quantile(array1,0.50))

Q2 3.0


In [11]:
print("Q3",np.quantile(array1,0.75))

Q3 4.0


In [12]:
array7=np.array([2,3,1,4,5])

In [13]:
print("Q1",np.quantile(array1,0.25))
print("Q2",np.quantile(array1,0.50))
print("Q3",np.quantile(array1,0.75))

Q1 2.0
Q2 3.0
Q3 4.0


###  Measures of dispersion

In [14]:
a=np.array([141,123,552,123,651,162])
print("Range",a.max()-a.min())

Range 528


In [15]:
#Variannce
print(array1)
print("Variance",np.var(array1))

[1 2 3 4 5]
Variance 2.0


In [16]:
print(array2)
print("Variance",np.var(array2))

[  1   2   3   4   5 500]
Variance 34308.47222222222


In [17]:
b=np.array([1.1,1.2,1.3,1.4,1.5])
print("Variance",np.var(b))

Variance 0.01999999999999999


In [18]:
print("Standard deviation",np.std(array1))

Standard deviation 1.4142135623730951


In [19]:
print("Standard deviation",np.std(array2))

Standard deviation 185.22546321233003


In [20]:
print("Standard deviation",np.std(b))

Standard deviation 0.14142135623730948


In [21]:
#Interquartile range
print(array1)
Q1=np.quantile(array1,0.25)
Q3=np.quantile(array1,0.75)
print("Q1",Q1)
print("Q3",Q3)
print("IOR",Q3-Q1)

[1 2 3 4 5]
Q1 2.0
Q3 4.0
IOR 2.0
